---
- id: check-openapi
  name: check-openapi
  entry: openapi-spec-validator
  description: >-
    Validate your OpenAPI/Swagger Specs with openapi-spec-validator in
    Pythn
  language: python
  files: (openapi|swagger).*\.(json|ya?ml)$
