---
- id: check-openapi
  name: check-openapi
  entry: openapi-spec-validator
  description: >-
    Validate your OpenAPI/Swagger Specs with openapi-spec-validator in
    Python
  language: python
  files: (openapi|swagger).*\.(json|ya?ml)$
- id: check-many-openapi
  name: check-many-openapi
  entry: check-many-openapi
  description: >-
    Validate your OpenAPI/Swagger Specs with openapi-spec-validator in
    Python--accepting multiple filenames as input
  language: python
  files: (openapi|swagger).*\.(json|ya?ml)$
