---
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v3.3.0"
  hooks:
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-yaml
    - id: check-json
    - id: debug-statements
    - id: double-quote-string-fixer
    - id: end-of-file-fixer
    - id: name-tests-test
    - id: requirements-txt-fixer
    - id: trailing-whitespace
