---
- id: check-openapi
  name: check-openapi
  entry: check-valid-openapi
  description: >-
    Validate your OpenAPI/Swagger Specs with openapi-spec-validator in
    Python
  language: python
  files: (openapi|swagger).*\.(json|ya?ml)$
